altura = float(input('Qual a altura da parede? '))
largura = float(input('Qual a largura da parede? '))
area = (altura*largura)
litros = (area/2)
print('A área da parede é {}m2.'.format(area))
print('São necessários {}l para pintar a parede!'.format(litros))
